FROM node:20.11.1-alpine3.19 AS build
WORKDIR /app
COPY package*.json .
RUN npm install @angular/cli -g
RUN npm install
COPY . .
RUN npm run build

# Serve Application using Nginx Server
FROM nginx:alpine
COPY --from=build /app/dist/dynamic-form-builder/ /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;"]